[package]
name = "authenticatooor"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
solana-program = "=1.13.5"
shank = "0.0.2"
borsh = "0.9.3"
thiserror = "~1.0"
num-derive = "0.3.3"
num-traits = "~0.2"
serde = { version = "1.0.147", features = ["derive"]}
serde_json = "1.0.87"


[features]
test-bpf = []

[dev-dependencies]
assert_matches = "1.5.0"
solana-program-test = "=1.13.5"
solana-sdk = "=1.13.5"
solana-validator = "=1.13.5"
solana-logger = "=1.13.5"
spl-token = "3.5.0"

[lib]
crate-type = ["cdylib", "lib"]
